# Generated by Django 5.0.2 on 2024-02-14 02:46

import django.db.models.deletion
import educate_portal.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Предмет обучения',
                'verbose_name_plural': 'Предмет обучения',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=250, verbose_name='Заголовок урока')),
                ('description', models.TextField(blank=True, max_length=5000, verbose_name='Описание урока')),
                ('description2', models.TextField(blank=True, max_length=5000, verbose_name='Продолжение описания')),
                ('position', models.PositiveSmallIntegerField(verbose_name='Номер урока')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='уникальное поле в адресной строке (eng раскладка)')),
                ('file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('ppt', models.FileField(blank=True, upload_to=educate_portal.models.save_lesson_files, verbose_name='презентации')),
                ('Notes', models.FileField(blank=True, upload_to=educate_portal.models.save_lesson_files, verbose_name='файл урока')),
                ('console', models.URLField(default='', max_length=250, verbose_name='консоль')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educate_portal.standard')),
            ],
            options={
                'verbose_name': 'Уроки',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm_name', models.CharField(blank=True, max_length=100)),
                ('body', models.TextField(max_length=500)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lesson_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='educate_portal.lesson')),
            ],
            options={
                'verbose_name': 'комментарии',
                'verbose_name_plural': 'комментарии',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_body', models.TextField(max_length=500, verbose_name='ответ на комментарий')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comment_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='educate_portal.comment')),
            ],
            options={
                'verbose_name': 'Ответы на комментарии',
                'verbose_name_plural': 'Ответы на комментарии',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to=educate_portal.models.save_subject_image, verbose_name='Subject Image')),
                ('description', models.TextField(blank=True, max_length=500)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='educate_portal.standard')),
            ],
            options={
                'verbose_name': 'Категория предмета обучения',
                'verbose_name_plural': 'Категория предмета обучения',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='educate_portal.subject'),
        ),
    ]
