# Generated by Django 4.1.6 on 2024-02-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='course_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название курса'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='is_teacher',
            field=models.BooleanField(default=False, verbose_name='Наставник'),
        ),
    ]
