# Generated by Django 4.1.6 on 2024-02-15 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_userprofileinfo_course_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='is_teacher',
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user_type',
            field=models.CharField(choices=[('teacher', 'Учитель'), ('student', 'Студент')], default='student', max_length=30, verbose_name='Тип пользователя'),
        ),
    ]
